# Generated by Django 2.1.2 on 2019-03-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceComments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_teacher_id', models.IntegerField(blank=True, null=True)),
                ('attitude', models.IntegerField(blank=True, null=True)),
                ('content', models.IntegerField(blank=True, null=True)),
                ('method', models.IntegerField(blank=True, null=True)),
                ('achievement', models.IntegerField(blank=True, null=True)),
                ('effect', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'db_table': 'choice_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_teacher_id', models.BigIntegerField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('recommend', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('num_valuable', models.IntegerField(blank=True, null=True)),
                ('num_happy', models.IntegerField(blank=True, null=True)),
                ('num_bad', models.IntegerField(blank=True, null=True)),
                ('num_score', models.IntegerField(blank=True, null=True)),
                ('lesson_name', models.CharField(blank=True, max_length=32, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTeacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=32, null=True)),
                ('lesson_name', models.CharField(blank=True, max_length=32, null=True)),
                ('introduction', models.CharField(blank=True, max_length=4096, null=True)),
                ('num_best', models.IntegerField(blank=True, null=True)),
                ('num_good', models.IntegerField(blank=True, null=True)),
                ('num_bad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
